---
title: "CompetingSims"
author: "Misha Dolmatov"
date: "2023-12-07"
output: html_document
---

```{r, include=FALSE}
library(tidyverse)
library(ggpubr)
library(lme4)
```


```{r test }
source("RandomEffectsAFT.R")
psi1 = c(-0.2, 0.3)
psi2 = c(0.4, -0.4)

train = sim_data(1000,psi1, psi2)
psi1_hat = aft(train, a~x+z, delta~x+z, log(Y)~ x+ a+a:x, 1)
psi2_hat = aft(train, a~x+z, delta~x+z, log(Y)~ x+ a+a:x, 2)

test = sim_data(1000, psi1, psi2, cens = F)
res = eval_DTR(train, test, psi1, psi2, psi1_hat, psi2_hat)
```



```{r baseline scenario, message = F, warning = F}
#Showcasing parameter estimation in a baseline scenario
#Should make variance smaller
#Both causes have same treatment basically so expect high POT, Value etc.
source("RandomEffectsAFT.R")

set.seed(2024)

n_rep = 100
n_test = 1000
n_train = 1000

psi1= c(0.7,-0.2)
psi2= c(0.7, 0.2)
  
test = sim_data(n_test, psi1, psi2, cens = F)

#List of model specifications
models = list(both = list(treat = a~x, cens = delta~x, out = log(Y)~ x+ a+a:x), treat = list(treat = a~x, cens = delta~x, out = log(Y)~ x+z+ a+a:x), 
                out = list(treat = a~x+z, cens = delta~x+z, out = log(Y)~ x+ a+a:x), none = list(treat = a~x+z, cens = delta~x+z, out = log(Y)~ x+z+ a+a:x))

#Initialize result list
res = list()
for(name in names(models)){
   res[[name]] = list(psi1_hat = NULL, psi2_hat = NULL,metrics = list(weighted = list(pot = NULL, value = NULL, blip = NULL), greedy = list(pot =NULL, value = NULL, blip =NULL)))
}


for(i in 1:n_rep){
  train = sim_data(n_train, psi1, psi2)
  
  #Get estimates of psi1, psi2 for all 4 model specifications for 16 total parameters
  #Both models misspecified, treatment, outcome or neither
  
  #list of formulas for model specification
  models = list(both = list(treat = a~x, cens = delta~x, out = log(Y)~ x+ a+a:x), treat = list(treat = a~x, cens = delta~x, out = log(Y)~ x+z+ a+a:x), 
                out = list(treat = a~x+z, cens = delta~x+z, out = log(Y)~ x+ a+a:x), none = list(treat = a~x+z, cens = delta~x+z, out = log(Y)~ x+z+ a+a:x))

  for (name in names(models)){
    model = models[[name]]
    psi1_hat = aft(train, model$treat, model$cens, model$out,1)
    psi2_hat = aft(train, model$treat, model$cens, model$out,2)
    res_DTR = eval_DTR(train, test, psi1, psi2, psi1_hat, psi2_hat)
    
    cur = res[[name]]
    updated_metrics = list(weighted = update_metrics(cur$metrics, res_DTR, "weighted"), greedy = update_metrics(cur$metrics, res_DTR, "greedy"))
    res[[name]] = list(psi1_hat = rbind(cur$psi1_hat, psi1_hat), psi2_hat = rbind(cur$psi2_hat, psi2_hat), metrics = updated_metrics)
  }
    
  
}

#Box plots for parameters
#For these, need to find a way to combine 

p1 = ggplot() + geom_hline(yintercept = psi1[1], linetype = 2) + labs(y = expression(hat(psi)[11]))
p2 = ggplot() + geom_hline(yintercept = psi1[2], linetype = 2) + labs(y = expression(hat(psi)[12]))

p3 = ggplot() + geom_hline(yintercept = psi2[1], linetype = 2) + labs(y = expression(hat(psi)[21]))
p4 = ggplot() + geom_hline(yintercept = psi2[2], linetype = 2) + labs(y = expression(hat(psi)[22]))

for(name in names(models)){
  p1 = p1 + geom_boxplot(data = res[[name]]$psi1_hat[,1] %>% as_tibble() %>% mutate(scenario = which(names(models) == name)), aes(x = scenario,y = value))
  p2 = p2 + geom_boxplot(data = res[[name]]$psi1_hat[,2] %>% as_tibble() %>% mutate(scenario = which(names(models) == name)), aes(x = scenario,y = value))
  
  p3 = p3 + geom_boxplot(data = res[[name]]$psi2_hat[,1] %>% as_tibble() %>% mutate(scenario = which(names(models) == name)), aes(x = scenario,y = value))
  p4 = p4 + geom_boxplot(data = res[[name]]$psi2_hat[,2] %>% as_tibble() %>% mutate(scenario = which(names(models) == name)), aes(x = scenario,y = value))
  
}

#Blip plots
#For these, can just loop through and get blips
for(name in names(models)){
  #Blip plots
  metrics = res[[name]]$metrics
  print(plot_results(test, metrics$weighted$blip, metrics$greedy$blip))
}

#Proportion of optimal treatment and value

#Bias and SE


ggsave("blip.png", r, width=12, height = 12)


```



```{r scenario 1, warning=F,fig.width= 10, fig.height=10}

#Scenario 1: Weighted performs the best
#When one cause is more likely, however less likely cause has very negative blips compared to most probable cause
#epsilon = rbinom(n,1,expit(x+0.5))+1
#x<- rbinom(n,1, 0.5)

source("RandomEffectsAFT.R")

set.seed(2024)

n_rep = 100
n_test = 1000
n_train = 500

psi1= c(2.2,-0.2)
psi2= c(-0.7, -0.2)
  
test = sim_data(n_test, cens = F, psi1, psi2)
res = list(psi1_hat = NULL, psi2_hat = NULL,metrics = list(weighted = list(pot = NULL, value = NULL, blip = NULL), greedy = list(pot =NULL, value = NULL, blip =NULL)))

#Estimation loop
for(i in 1:n_rep){
  train = sim_data(n_train, psi1, psi2)

  model = list(treat = a~x+z, cens = delta~x+z, out = log(Y)~ x+z+ a+a:x)
  psi1_hat = aft(train, model$treat, model$cens, model$out,1)
  psi2_hat = aft(train, model$treat, model$cens, model$out,2)
  res_DTR = eval_DTR(train, test, psi1, psi2, psi1_hat, psi2_hat)
    
  cur = res
  updated_metrics = list(weighted = update_metrics(cur$metrics, res_DTR, "weighted"), greedy = update_metrics(cur$metrics, res_DTR, "greedy"))
  res = list(psi1_hat = rbind(cur$psi1_hat, psi1_hat), psi2_hat = rbind(cur$psi2_hat, psi2_hat), metrics = updated_metrics)
    
}


#Blip plot
print(plot_results(test, res$metrics$weighted$blip, res$metrics$greedy$blip))

#POT, Value
colMeans(cbind(res$metrics$weighted$pot,res$metrics$greedy$pot))
colMeans(cbind(res$metrics$weighted$value,res$metrics$greedy$value))

#Bias, SE
bias_SE(cbind(res$psi1_hat,res$psi2_hat),  c(psi1, psi2))

#Save plot
#ggsave("blip1.png", r.1, width=12, height = 12)

#r.1
```


```{r scenario 2, warning=F, fig.width= 10, fig.height=10}
source("RandomEffectsAFT.R")

#Scenario 3 : Greedy performs the best
#When one cause is more likely and the less likely cause does not have very negative blips
#epsilon = rbinom(n,1,expit(x+0.5))+1
set.seed(2024)

n_rep = 200
n_test = 1000
n_train = 500


psi1_fixed= c(-0.6, -0.7)
psi2_fixed= c(0.1, 0.08)

test = sim_data(n_test, cens = F, psi1_fixed, psi2_fixed)

res = matrix(0, nrow = n_rep, ncol = 2*n_test + 4)
param = matrix(0, nrow = n_rep, ncol = 4)

for(i in 1:n_rep){
  train = sim_data(n_train, cens = T, psi1_fixed, psi2_fixed)
  psi_hat = aft_gee(train)
  
  res[i,] = sim_stochastic_regime(train, test, psi1_fixed, psi2_fixed, psi_hat[c(1,2)], psi_hat[c(3,4)])
  param[i,] = psi_hat
}

plots2 =plot_results(res, test)

#POT, Value, Bias and SE

colMeans(plots2[[2]])
plots2[[3]]
tab2 = bias_SE(param, c(psi1_fixed, psi2_fixed))

r.2 =plots2[[1]]
ggsave("blip2.png", r.2, width=12, height = 12)

r.2
```

```{r scenario 3 same slopes & perform similar}
#Need to pick values that do not have that much variance, so that the actual differences are more apparent

source("RandomEffectsAFT.R")

#Scenario 3 : Same slopes and similar performance for both regimes
#And small ICC = 0.5
#epsilon = rbinom(n,1,expit(x+0.5))+1
set.seed(2024)

n_rep = 200
n_test = 1000
n_train = 500


psi1_fixed= c(0.3,-0.3)
psi2_fixed= c(-0.3, -0.3)

test = sim_data(n_test, cens = F, psi1_fixed, psi2_fixed)

res = matrix(0, nrow = n_rep, ncol = 2*n_test + 4)
param = matrix(0, nrow = n_rep, ncol = 4)

for(i in 1:n_rep){
  train = sim_data(n_train, cens = T, psi1_fixed, psi2_fixed)
  psi_hat = aft_gee(train)
  
  res[i,] = sim_stochastic_regime(train, test, psi1_fixed, psi2_fixed, psi_hat[c(1,2)], psi_hat[c(3,4)])
  param[i,] = psi_hat
}

plots3 =plot_results(res, test)

#POT, Value, Bias and SE

colMeans(plots3[[2]])
plots3[[3]]
tab3 = bias_SE(param, c(psi1_fixed, psi2_fixed))

r.3 =plots3[[1]]
ggsave("blip3.png", r.3, width=12, height = 12)
r.3
```


```{r scenario 4 different ICC, warning = F, message = F}
source("RandomEffectsAFT.R")

#Scenario 4: Different ICC
#Maybe change ICC but make the sum of random effect and aft variances equal so total variance is the same
# now we go ICC approx 0.9, which corresponds to sd of 0.67 and 0.22 for re and model respectively

set.seed(2024)

n_rep = 200
n_test = 1000
n_train = 500


psi1_fixed= c(0.3,-0.3)
psi2_fixed= c(-0.3, -0.3)

test = sim_data(n_test, cens = F, psi1_fixed, psi2_fixed)

res = matrix(0, nrow = n_rep, ncol = 2*n_test + 4)
param = matrix(0, nrow = n_rep, ncol = 4)

for(i in 1:n_rep){
  train = sim_data(n_train, cens = T, psi1_fixed, psi2_fixed)
  psi_hat = aft_gee(train)
  
  res[i,] = sim_stochastic_regime(train, test, psi1_fixed, psi2_fixed, psi_hat[c(1,2)], psi_hat[c(3,4)])
  param[i,] = psi_hat
}

plots4 =plot_results(res, test)

#POT, Value, Bias and SE

colMeans(plots4[[2]])
plots4[[3]]
tab4 = bias_SE(param, c(psi1_fixed, psi2_fixed))

r.4 =plots4[[1]]
ggsave("blip4.png", r.4, width=12, height = 12)

r.4
```

```{r scenario 5 different error distribution}
source("RandomEffectsAFT.R")

#Scenario 5: Different error distribution
#Gonna use centered gamma distribution with beta = 1 and alpha = 0.25, rgamma(n, shape = 0.25) - 0.25
#should pick one with similar variance as to not affect value all that much
#Also pick values of psi to make situation where increased standard error affects POT/Value
#i.e. one where larger error bars make regimes cross 0 when they shouldnt

set.seed(2024)

n_rep = 200
n_test = 1000
n_train = 500


psi1_fixed= c(0.3,-0.3)
psi2_fixed= c(-0.3, -0.3)

test = sim_data(n_test, cens = F, psi1_fixed, psi2_fixed)

res = matrix(0, nrow = n_rep, ncol = 2*n_test + 4)
param = matrix(0, nrow = n_rep, ncol = 4)

for(i in 1:n_rep){
  train = sim_data(n_train, cens = T, psi1_fixed, psi2_fixed)
  psi_hat = aft_gee(train)
  
  res[i,] = sim_stochastic_regime(train, test, psi1_fixed, psi2_fixed, psi_hat[c(1,2)], psi_hat[c(3,4)])
  param[i,] = psi_hat
}

plots5 =plot_results(res, test)

#POT, Value, Bias and SE

colMeans(plots5[[2]])
plots5[[3]]
tab5=bias_SE(param, c(psi1_fixed, psi2_fixed))

r.5 =plots5[[1]]
ggsave("blip5.png", r.5, width=12, height = 12)

r.5
```

```{r scenario 6 different level of censoring}
source("RandomEffectsAFT.R")

#Scenario 6: 70% censoring instead of 25% -> switch intercept in censoring model to 1 instead of 1.9
set.seed(2024)

n_rep = 200
n_test = 1000
n_train = 500


psi1_fixed= c(0.3,-0.3)
psi2_fixed= c(-0.3, -0.3)

test = sim_data(n_test, cens = F, psi1_fixed, psi2_fixed)

res = matrix(0, nrow = n_rep, ncol = 2*n_test + 4)
param = matrix(0, nrow = n_rep, ncol = 4)

for(i in 1:n_rep){
  train = sim_data(n_train, cens = T, psi1_fixed, psi2_fixed)
  psi_hat = aft_gee(train)
  
  res[i,] = sim_stochastic_regime(train, test, psi1_fixed, psi2_fixed, psi_hat[c(1,2)], psi_hat[c(3,4)])
  param[i,] = psi_hat
}

plots6 =plot_results(res, test)

#POT, Value, Bias and SE

colMeans(plots6[[2]])
plots6[[3]]
tab6 = bias_SE(param, c(psi1_fixed, psi2_fixed))

r.6 =plots6[[1]]
ggsave("blip6.png", r.6, width=12, height = 12)

r.6
```

```{r scenario 7 ignoring clustering}
source("RandomEffectsAFT.R")

#Scenario 7: ignoring clustering i.e. use independence structure in GEE over exchangeable
set.seed(2024)

n_rep = 200
n_test = 1000
n_train = 500


psi1_fixed= c(0.3,-0.3)
psi2_fixed= c(-0.3, -0.3)

test = sim_data(n_test, cens = F, psi1_fixed, psi2_fixed)

res = matrix(0, nrow = n_rep, ncol = 2*n_test + 4)
param = matrix(0, nrow = n_rep, ncol = 4)

for(i in 1:n_rep){
  train = sim_data(n_train, cens = T, psi1_fixed, psi2_fixed)
  psi_hat = aft_gee(train)
  
  res[i,] = sim_stochastic_regime(train, test, psi1_fixed, psi2_fixed, psi_hat[c(1,2)], psi_hat[c(3,4)])
  param[i,] = psi_hat
}

plots7 =plot_results(res, test)

#POT, Value, Bias and SE

colMeans(plots7[[2]])
plots7[[3]]
tab7=bias_SE(param, c(psi1_fixed, psi2_fixed))

r.7 =plots7[[1]]
ggsave("blip7.png", r.7, width=12, height = 12)

r.7
```

```{r scenario 8 clustering in the treatment allocation}
#Scenario : ignoring treatment clustering
source("RandomEffectsAFT.R")

set.seed(2024)

n_rep = 200
n_test = 1000
n_train = 500


psi1_fixed= c(0.3,-0.3)
psi2_fixed= c(-0.3, -0.3)

test = sim_data(n_test, cens = F, psi1_fixed, psi2_fixed)

res = matrix(0, nrow = n_rep, ncol = 2*n_test + 4)
param = matrix(0, nrow = n_rep, ncol = 4)

for(i in 1:n_rep){
  train = sim_data(n_train, cens = T, psi1_fixed, psi2_fixed)
  psi_hat = aft_gee(train)
  
  res[i,] = sim_stochastic_regime(train, test, psi1_fixed, psi2_fixed, psi_hat[c(1,2)], psi_hat[c(3,4)])
  param[i,] = psi_hat
}

plots8 =plot_results(res, test)

#POT, Value, Bias and SE

colMeans(plots8[[2]])
plots8[[3]]
tab8 =bias_SE(param, c(psi1_fixed, psi2_fixed))

r.8 =plots8[[1]]
ggsave("blip8.png", r.8, width=12, height = 12)

r.8
```


TO DO : 

3 different levels of clustering in treatment??
Note: 


For plots, should we put the estimated blip or the true blip for weighted/greedy regimes? 

Estimated cause it tells us what is the actual cause for performance we see in metrics? 




